PARAGRAPH_LENGTH = 200

NUM_FEATURES = 50
MIN_WORD_COUNT = 1
CONTEXT_SIZE = 7
DOWNSAMPLING = 1e-1


__all__ = [
    'PARAGRAPH_LENGTH',
    'NUM_FEATURES',
    'MIN_WORD_COUNT',
    'CONTEXT_SIZE',
    'DOWNSAMPLING'
]